version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: cd android
            - run:
                name: Set ANDROID_HOME
                command:  echo sdk.dir = $ANDROID_HOME > local.properties
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - run:
                name: Export Path
                command: export PATH=~/.local/bin:$PATH
            - run:
                name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
                command: sudo chmod +x ./gradlew
            - run:
                name: Build APKS
                command: ./gradlew --info assembleRelease
            - store_artifacts:
                path: app/build/outputs/apk
                destination: reports
#            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
